# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Directory path containing version-specific properties files for Minecraft
version_properties_path=./properties

# Mod Properties
mod_version=1.2.1
maven_group=cn.revaria.chatplus
archives_base_name=chat-plus

# Minecraft
minecraft_version=26.2

# Override Fabric API version for local testing (runClient/runServer)
#test_fabric_api_version=

# Dependencies
manifold_version=2025.1.25
