java_version=17

# Fabric Loom
# - For Minecraft versions <26.1: enable remap
# - For Minecraft versions >=26.1: disable remap
fabric_loom_remap=true

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_loader_version=0.16.10
min_fabric_loader_version=
fabric_api_version=0.58.4
# Fabric API mod ID conventions:
# - For Minecraft versions <1.19.2: use "fabric"
# - For Minecraft versions >=1.19.2: use "fabric-api"
# Ref: https://wiki.fabricmc.net/tutorial:setup
fabric_api_mod_id=fabric

# Mod Compatibility
! Dynmap 3.7-beta-4
mod_dynmap_version=c0uFN8Lt
! Styled Chat 1.4.0+1.19.1
mod_styled_chat_version=1.4.0+1.19.1
mod_styled_chat_placeholder_api_version=2.0.0-beta.7+1.19
