java_version=21

# Fabric Loom
# - For Minecraft versions <26.1: enable remap
# - For Minecraft versions >=26.1: disable remap
fabric_loom_remap=true

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_loader_version=0.16.10
min_fabric_loader_version=
fabric_api_version=0.100.1
# Fabric API mod ID conventions:
# - For Minecraft versions <1.19.2: use "fabric"
# - For Minecraft versions >=1.19.2: use "fabric-api"
# Ref: https://wiki.fabricmc.net/tutorial:setup
fabric_api_mod_id=fabric-api

# Mod Compatibility
! Dynmap 3.7-beta-8
mod_dynmap_version=1pMUPhY2
! Styled Chat 2.6.1+1.21
mod_styled_chat_version=2.6.1+1.21
mod_styled_chat_placeholder_api_version=2.4.2+1.21
