java_version=25

# Fabric Loom
# - For Minecraft versions <26.1: enable remap
# - For Minecraft versions >=26.1: disable remap
fabric_loom_remap=false

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_loader_version=0.19.1
min_fabric_loader_version=
fabric_api_version=0.144.0
# Fabric API mod ID conventions:
# - For Minecraft versions <1.19.2: use "fabric"
# - For Minecraft versions >=1.19.2: use "fabric-api"
# Ref: https://wiki.fabricmc.net/tutorial:setup
fabric_api_mod_id=fabric-api

# Mod Compatibility
! Dynmap 3.8
mod_dynmap_version=4UHHD4t6
! Styled Chat 2.12.0-pre.1+26.1
mod_styled_chat_version=2.12.0-pre.1+26.1
mod_styled_chat_placeholder_api_version=3.0.0-beta.2+26.1
